name: Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -o wordprinter

    - name: Push to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: wordprinter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
